version: '3'
services:
    museum-service:
        build: .
        volumes:
          - ./app:/app
        depends_on:
          - db-service

    db-service:
        restart: always
        image: postgres
        volumes:
          - /home/ec2-user/db/:/var/lib/postgresql/data/
        ports:
          - 5432:5432