version: '3'
services:
    museum-service:
        build: .
        depends_on:
          - db-service

    db-service:
        restart: always
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: db_museum
        volumes:
          - /home/ec2-user/db/:/var/lib/postgresql/data/
        ports:
          - 5432:5432
